a=10;
document.write("Result:<br>The value of a is "+a);
document.write("<br><br>+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++<br><br>");
b=++a;
document.write("<br>The value of ++a is "+ a);
document.write("<br>Now the value of a is "+b);
document.write("<br><br>");
b=a++;
document.write("<br>The value of a++ is "+ b);
document.write("<br>Now the value of a is "+ a);
document.write("<br><br>");
b=--a;
document.write("<br>The value of --a is "+ b);
document.write("<br>Now the value of a is "+a);
document.write("<br><br>");
b=a--;
document.write("<br>The value of a-- is "+ b);
document.write("<br>Now the value of a is "+a);
