var a;
document.write("Value after variable declaration is "+a);
a=5;
document.write("<br>Initial value: "+a);
a++;
document.write("<br>Value after increment is: "+a);
a+=7;
document.write("<br>Value after addition is: "+a);
a--;
document.write("<br>Value after decremnet is: "+a);
document.write("<br>The remainder is: "+a%3);
